### ISSUE TITLE
`:+1` at the beginning of a message prevents message from sending

### ISSUE THREAD

**Issue by crookedneighbor** [Horacious/HabitRPG-Chat-Extension#17]
Was trying to type the thumbsup up alias, `:+1:` (:+1:) in the chat window, and it wouldn't let me send the message if it was the beginning of the input. Here's what my testing revealed:

`:+1: anything else` - did not work
`:+1 anything else` - did not work
`:+1` - did not work
`:: with or without extra text` - works
`:+: with or without extra text` - works
`:1: with or without extra text` - works
`Some text before :+1: with or without extra text` - works

It's only messages that begin with `:+1` that is the problem.

**Comment by FriendlyPopo** [comment]
Fixed - added ":" to message validation regex
