### ISSUE TITLE
Suggestion: mention highlight

### ISSUE THREAD

**Issue by bTackt** [Horacious/HabitRPG-Chat-Extension#28]
I've not seen the code for how Habit does this, and so I'm not sure how hard it would be (if you can just copy it with slight modifications?), but having messages somehow highlighted if you're mentioned in them would be cool.

**Comment by crookedneighbor** [comment]
Shouldn't be too hard actually. Just need to do a regex search of the message and see if the user's name is contained in it.

**Comment by FriendlyPopo** [comment]
Definitely agree that this is a good feature that wouldn't be too hard.

A CSS border should do it?

**Comment by crookedneighbor** [comment]
It should definitely be more attractive then the website version IMO

**Comment by FriendlyPopo** [comment]
Can you detail "more attractive"? Any ideas? Maybe a different bubble color?

**Comment by crookedneighbor** [comment]
I just don't like the gray color that is being used on the website. Got to be a better way of indicating it then a gray background color. (Careful, I might steal whatever you come up with for the site :wink:)

**Comment by FriendlyPopo** [comment]
Cool - if you like the idea, however, I'd love it if you let me change it in the site, though! Would be an easy first contribution.

**Comment by crookedneighbor** [comment]
:+1:

**Comment by FriendlyPopo** [comment]
@crookedneighbor , @knittingfrenzy18 I added highlighting of @ mentions + a nifty little nav that allows you to skim through mentions.  I'm not sure about how it's positioned, however. Can you provide feedback?

![image](https://cloud.githubusercontent.com/assets/11324453/6611812/d08ecbde-c847-11e4-896b-f429aecd6cda.png)
