### ISSUE TITLE
Cannot load certain guild chat

### ISSUE THREAD

**Issue by Blauelf** [Horacious/HabitRPG-Chat-Extension#30]
Hi,
when I want to load chat from '📜 Library of Shared Lists' and 'Fitocracy' guild, it stays in 'Loading chat...', printing an `Uncaught TypeError: Cannot convert undefined or null to object` in `(index):1` on console. The 'scroll' guild additionally gives repeating `Uncaught TypeError: Cannot convert undefined or null to object` in `(index):1`, each followed by a `GET https://habitrpg.com/link 404 (Not Found)` in `link:1`.
Works fine when loading these particular guilds' chat on the website, works fine when loading chat from any other of my guilds (I cannot test party chat since I do not have one yet).

I have already deactivated all extensions, some of which may interfere (for example, "Send to Google Drive" did, due to loading a superfish script via HTTP into HTTPS site thus violating mixed-origin policy).

**Comment by FriendlyPopo** [comment]
Thanks for submitting a bug!

Do you have the latest productino version installed? (0.5.6)

I pushed a fix for an issue with some guilds, yesterday - might fix it. Please make sure you have latest (if not, remove extension and download from chrome Webstore), and if the problem persists I will investigate.

**Comment by Blauelf** [comment]
Yes, 0.5.6 is installed and is currently latest version as to chrome webstore. Can you replicate the problem, or is there anything I can do to further examine it? I have no idea what's going on and do not know if the problems with both groups are even closely related.

**Comment by FriendlyPopo** [comment]
There was an issue with the likes counter with chat messages that didn't have the like property. It's fixed in 0.6.1 which I'll be putting live now and should be available in the Chrome store in the coming hour. Please check if it works and, if so, close the bug.

Thanks!

**Comment by Blauelf** [comment]
Guild chat loading now, the 'scroll' guild is still spamming the console with that link error, but at the moment I do not see any real problems other than the console getting spammed :)

Thank you for the quick fix!
