### ISSUE TITLE
Allows script injection

### ISSUE THREAD

**Issue by gisikw** [Horacious/HabitRPG-Chat-Extension#35]
Hiya,

Chat messages have HTML escaped within the HabitRPG code, but it appears that's not the case within the extension.

Sample Guild message: `<script>alert("Broke it")</script>`

**Comment by FriendlyPopo** [comment]
Oh dear - how amateurish.

Fixed in 1.2, and thanks for the hint!

**Comment by crookedneighbor** [comment]
Personally, I think we should be sanitizing all strings before saving them to the HRPG db.

@gisikw Do you have thoughts on this?

**Comment by gisikw** [comment]
That makes sense to me!
