### ISSUE TITLE
habitrpg.com switch to habitica.com

### ISSUE THREAD

**Issue by ghost** [Horacious/HabitRPG-Chat-Extension#36]
Habitrpg.com is switching to habitica.com as of 7/31, and the chat extension doesn't work over there yet.  It looks like it might just be a quick fix to the matching urls and account linking url?

Thanks for making a great extension - it's been super useful so far!
~studentSeekingDiscipline

**Comment by FriendlyPopo** [comment]
Thanks for the praise!

@crookedneighbor's update has been pushed to production. Chrome should update it automatically in the next 24h.
