### ISSUE TITLE
A solution to make nametagging ( @ ) easier

### ISSUE THREAD

**Issue by FriendlyPopo** [Horacious/HabitRPG-Chat-Extension#5]
Blade suggestions clicking on a users' name adds it to the text area. Makes sense!

**Comment by crookedneighbor** [comment]
The other option is to have a reply button.

**Comment by FriendlyPopo** [comment]
Would leave room for eventual "click name to view profile". That being
said, I like "click name to @mention" better because it feels more
intuitive a way to mention more people.

**Comment by crookedneighbor** [comment]
That's true. You could also put an `@` button in front of the name.

**Comment by FriendlyPopo** [comment]
Opted for clicking name adds @ mention for simplicity. I couldn't figure out how to generate the "view profile" pop up.
